name: CI - Docker Build & Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create backend .env from GitHub Secrets
        run: |
          echo "PORT=3000" > ./rotaflow-backend/.env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> ./rotaflow-backend/.env

      - name: Build Docker images
        run: |
          docker-compose build

      - name: Start services
        run: |
          docker-compose up -d
          sleep 20 # give backend time to connect to NeonDB

      - name: Check backend health (inside container)
        run: |
          docker-compose exec -T backend curl -f http://localhost:3000/api/health || exit 1

      - name: Check frontend health (inside container)
        run: |
          docker-compose exec -T frontend curl -f http://localhost:80 || exit 1

      - name: Stop services
        run: docker-compose down

      # ---- Deployment (disabled for now) ----
      # - name: Deploy to VPS
      #   run: |
      #     ssh user@your-vps-ip "cd /path/to/app && git pull && docker-compose up -d --build"
