name: CI - Docker Build & Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create backend .env from GitHub Secrets
        run: |
          echo "PORT=3000" > ./rotaflow-backend/.env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> ./rotaflow-backend/.env

      - name: Build Docker images
        run: docker-compose build

      - name: Start services
        run: docker-compose up -d

      - name: Wait for backend to be ready
        run: |
          for i in {1..20}; do
            if docker-compose exec -T backend curl -s http://localhost:3000/api/health; then
              echo "✅ Backend is up!"
              exit 0
            fi
            echo "⏳ Waiting for backend... ($i/20)"
            sleep 3
          done
          echo "❌ Backend failed to start in time"
          exit 1

      - name: Wait for frontend to be ready
        run: |
          for i in {1..20}; do
            if docker-compose exec -T frontend curl -s http://localhost:80; then
              echo "✅ Frontend is up!"
              exit 0
            fi
            echo "⏳ Waiting for frontend... ($i/20)"
            sleep 3
          done
          echo "❌ Frontend failed to start in time"
          exit 1

      - name: Stop services
        run: docker-compose down
