name: CI - Docker Build & Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker images
        run: |
          docker-compose build

      - name: Start services
        run: |
          docker-compose up -d
          sleep 10 # wait for containers to be ready

      - name: Check backend health
        run: |
          curl -f http://localhost:3000/api/health || exit 1

      - name: Check frontend health
        run: |
          curl -f http://localhost:8080 || exit 1

      - name: Stop services
        run: docker-compose down

      # ---- Deployment (disabled for now) ----
      # - name: Deploy to VPS
      #   run: |
      #     ssh user@your-vps-ip "cd /path/to/app && git pull && docker-compose up -d --build"
